<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class PelangganSeeder extends Seeder
{
    public function run()
    {
        DB::table('pelanggan')->insert([
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'pelanggan',
                'username' => 'pelanggan',
                'password' => Hash::make('pelanggan'),
                'no_whatsapp' => '6281111111111',
                'alamat' => 'Jl. Raya No. 1',
                'tanggal_gabung' => '2024-01-01',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Siti Aminah',
                'username' => 'siti_aminah',
                'password' => Hash::make('siti_aminah'),
                'no_whatsapp' => '6281111111112',
                'alamat' => 'Jl. Raya No. 2',
                'tanggal_gabung' => '2024-01-05',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 3,
                'nama_pelanggan' => 'Andi Prasetyo',
                'username' => 'andi_p',
                'password' => Hash::make('andi_p'),
                'no_whatsapp' => '6281111111113',
                'alamat' => 'Jl. Raya No. 3',
                'tanggal_gabung' => '2024-01-10',
                'status_pelanggan' => 'arsip',
            ],
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'Dewi Lestari',
                'username' => 'dewi_l',
                'password' => Hash::make('dewi_l'),
                'no_whatsapp' => '6281111111114',
                'alamat' => 'Jl. Raya No. 4',
                'tanggal_gabung' => '2024-01-15',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Rudi Hartono',
                'username' => 'rudi_h',
                'password' => Hash::make('rudi_h'),
                'no_whatsapp' => '6281111111115',
                'alamat' => 'Jl. Raya No. 5',
                'tanggal_gabung' => '2024-01-20',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 3,
                'nama_pelanggan' => 'Siti Nurhaliza',
                'username' => 'siti_n',
                'password' => Hash::make('siti_n'),
                'no_whatsapp' => '6281111111116',
                'tanggal_gabung' => '2024-01-25',
                'alamat' => 'Jl. Raya No. 6',
                'status_pelanggan' => 'arsip',
            ],
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'Joko Susilo',
                'username' => 'joko_s',
                'password' => Hash::make('joko_s'),
                'no_whatsapp' => '6281111111117',
                'tanggal_gabung' => '2024-02-01',
                'alamat' => 'Jl. Raya No. 7',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Rina Wulandari',
                'username' => 'rina_w',
                'password' => Hash::make('rina_w'),
                'no_whatsapp' => '6281111111118',
                'alamat' => 'Jl. Raya No. 8',
                'tanggal_gabung' => '2024-02-05',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 3,
                'nama_pelanggan' => 'Agus Setiawan',
                'username' => 'agus_s',
                'password' => Hash::make('agus_s'),
                'no_whatsapp' => '6281111111119',
                'alamat' => 'Jl. Raya No. 9',
                'tanggal_gabung' => '2024-02-10',
                'status_pelanggan' => 'arsip',
            ],
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'Tina Sari',
                'username' => 'tina_s',
                'password' => Hash::make('tina_s'),
                'no_whatsapp' => '6281111111120',
                'alamat' => 'Jl. Raya No. 10',
                'tanggal_gabung' => '2024-02-15',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Dian Paramita',
                'username' => 'dian_p',
                'password' => Hash::make('dian_p'),
                'alamat' => 'Jl. Raya No. 11',
                'no_whatsapp' => '6281111111121',
                'tanggal_gabung' => '2024-02-20',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 3,
                'nama_pelanggan' => 'Yusuf Hamzah',
                'username' => 'yusuf_h',
                'password' => Hash::make('yusuf_h'),
                'alamat' => 'Jl. Raya No. 12',
                'no_whatsapp' => '6281111111122',
                'tanggal_gabung' => '2024-02-25',
                'status_pelanggan' => 'arsip',
            ],
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'Lina Marlina',
                'username' => 'lina_m',
                'password' => Hash::make('lina_m'),
                'no_whatsapp' => '6281111111123',
                'alamat' => 'Jl. Raya No. 13',
                'tanggal_gabung' => '2024-03-01',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Wawan Kurniawan',
                'username' => 'wawan_k',
                'password' => Hash::make('wawan_k'),
                'no_whatsapp' => '6281111111124',
                'alamat' => 'Jl. Raya No. 14',
                'tanggal_gabung' => '2024-03-05',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 3,
                'nama_pelanggan' => 'Fitri Handayani',
                'username' => 'fitri_h',
                'password' => Hash::make('fitri_h'),
                'no_whatsapp' => '6281111111125',
                'alamat' => 'Jl. Raya No. 15',
                'tanggal_gabung' => '2024-03-10',
                'status_pelanggan' => 'arsip',
            ],
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'Hendra Saputra',
                'username' => 'hendra_s',
                'password' => Hash::make('hendra_s'),
                'no_whatsapp' => '6281111111126',
                'alamat' => 'Jl. Raya No. 16',
                'tanggal_gabung' => '2024-03-15',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Mega Pratiwi',
                'username' => 'mega_p',
                'password' => Hash::make('mega_p'),
                'no_whatsapp' => '6281111111127',
                'alamat' => 'Jl. Raya No. 17',
                'tanggal_gabung' => '2024-03-20',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 3,
                'nama_pelanggan' => 'Fahmi Ramadhan',
                'username' => 'fahmi_r',
                'password' => Hash::make('fahmi_r'),
                'no_whatsapp' => '6281111111128',
                'alamat' => 'Jl. Raya No. 18',
                'tanggal_gabung' => '2024-03-25',
                'status_pelanggan' => 'arsip',
            ],
            [
                'id_paket' => 1,
                'nama_pelanggan' => 'Yuni Astuti',
                'username' => 'yuni_a',
                'password' => Hash::make('yuni_a'),
                'no_whatsapp' => '6281111111129',
                'alamat' => 'Jl. Raya No. 19',
                'tanggal_gabung' => '2024-04-01',
                'status_pelanggan' => 'aktif',
            ],
            [
                'id_paket' => 2,
                'nama_pelanggan' => 'Tommy Wicaksono',
                'username' => 'tommy_w',
                'password' => Hash::make('tommy_w'),
                'no_whatsapp' => '6281111111130',
                'alamat' => 'Jl. Raya No. 20',
                'tanggal_gabung' => '2024-04-05',
                'status_pelanggan' => 'aktif',
            ],
        ]);
    }
}
